---

storage: ./storage

telegram:
  # Get one at @BotFather
  token: ''
  # Send message in your channel/group, then query
  #   https://api.telegram.org/bot{BOT_TOKEN}/getUpdates
  target_id: ''

resources:
  # bash.im
  - url: https://bash.im/
    target: 'main > section > article.quote > div.quote_frame > header.quote__header > a.quote__header_permalink'

  # Stopgame Blogs
  - url: https://stopgame.ru/blogs
    target: 'div.lent-left > div.blog-block > table.by-sides.blog-block-top > tbody > tr > td.title > a'
